// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr10mLstjgQBm-yrPy4SjHMfwBYjlDdSk',
    appId: '1:778970187906:web:b5351d0c1968326eac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    authDomain: 'devpedia-8231d.firebaseapp.com',
    storageBucket: 'devpedia-8231d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsq-wLa1OeJWoZZDeWX_ibzZrO87fSnz4',
    appId: '1:778970187906:android:3d889906f0f5aae8ac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6DhZgMBBo7kZ1wvEJgtCVnMWQBTL3H4',
    appId: '1:778970187906:ios:836ed787a739a67bac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.firebasestorage.app',
    androidClientId: '778970187906-dovu7inn12jbp3c92213qrh5e2mg9b61.apps.googleusercontent.com',
    iosClientId: '778970187906-uli1bnltenl9k5jfa3kv9edud7lgpmgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6DhZgMBBo7kZ1wvEJgtCVnMWQBTL3H4',
    appId: '1:778970187906:ios:836ed787a739a67bac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.firebasestorage.app',
    androidClientId: '778970187906-dovu7inn12jbp3c92213qrh5e2mg9b61.apps.googleusercontent.com',
    iosClientId: '778970187906-uli1bnltenl9k5jfa3kv9edud7lgpmgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr10mLstjgQBm-yrPy4SjHMfwBYjlDdSk',
    appId: '1:778970187906:web:7b683138472d65abac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    authDomain: 'devpedia-8231d.firebaseapp.com',
    storageBucket: 'devpedia-8231d.firebasestorage.app',
  );

}