// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC47WA7ynyLKGRaOlj2_M3O2axDF46m9DA',
    appId: '1:778970187906:web:fc046c04c21def51ac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    authDomain: 'devpedia-8231d.firebaseapp.com',
    storageBucket: 'devpedia-8231d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsq-wLa1OeJWoZZDeWX_ibzZrO87fSnz4',
    appId: '1:778970187906:android:6730cd228bb3ff20ac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6DhZgMBBo7kZ1wvEJgtCVnMWQBTL3H4',
    appId: '1:778970187906:ios:59240983ada35137ac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.appspot.com',
    iosBundleId: 'com.example.devpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6DhZgMBBo7kZ1wvEJgtCVnMWQBTL3H4',
    appId: '1:778970187906:ios:6b482117f5a2d674ac4c9b',
    messagingSenderId: '778970187906',
    projectId: 'devpedia-8231d',
    storageBucket: 'devpedia-8231d.appspot.com',
    iosBundleId: 'com.example.devpedia.RunnerTests',
  );
}
